const { Octokit } = require('@octokit/rest');
const fs = require('fs');
const path = require('path');

/**
 * Applies changes by committing the modified files and opening a PR.
 * @param {Object} config - The configuration object.
 * @param {string[]} changedFiles - Array of file paths (relative to repo root) that were modified.
 * @param {string} missionTitle - The title for the commit and PR.
 */
async function applyChangesAndOpenPR(config, changedFiles, missionTitle) {
  const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
  const { owner, repo, baseBranch } = config.github;
  const branchName = `visCarma/${Date.now()}`;

  // 1. Get the SHA of the base branch
  const { data: baseRef } = await octokit.git.getRef({
    owner, repo, ref: `heads/${baseBranch}`
  });

  // 2. Create a new branch
  await octokit.git.createRef({
    owner, repo, ref: `refs/heads/${branchName}`, sha: baseRef.object.sha
  });

  // 3. For each changed file, read its content and commit it
  for (const filePath of changedFiles) {
    const localPath = path.join(config.repoPath, filePath);
    // Skip directories
    if (fs.existsSync(localPath) && fs.statSync(localPath).isDirectory()) {
      console.warn(`⚠️ Skipping directory: ${filePath}`);
      continue;
    }
    if (!fs.existsSync(localPath)) {
      console.warn(`⚠️ File ${localPath} does not exist, skipping.`);
      continue;
    }
    const content = fs.readFileSync(localPath, 'utf8');
    const base64Content = Buffer.from(content).toString('base64');

    // Try to get the file's SHA from the branch (if it already exists)
    let fileSha;
    try {
      const { data: fileData } = await octokit.repos.getContent({
        owner, repo, path: filePath, ref: branchName
      });
      fileSha = fileData.sha;
    } catch {
      // File doesn't exist on the branch yet – that's fine
    }

    // Create or update the file
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: filePath,
      message: `VisCarma: ${missionTitle}`,
      content: base64Content,
      branch: branchName,
      ...(fileSha ? { sha: fileSha } : {})
    });
  }

  // 4. Create the pull request
  const pr = await octokit.pulls.create({
    owner,
    repo,
    title: `VisCarma: ${missionTitle}`,
    head: branchName,
    base: baseBranch,
    body: `Auto‑generated by VisCarma.\n\nMission: ${missionTitle}`
  });

  console.log(`✅ PR created: ${pr.data.html_url}`);
  return pr.data.html_url;
}

module.exports = { applyChangesAndOpenPR };